### PR TITLE
STREAMS-432 Update to Java 8

### PR DESCRIPTION
**Pull request by jfrazee**

### CODE REVIEW

**Comment by steveblackmon** [comment]
👍

**Comment by steveblackmon** [comment]
this merged to asf - should auto-close once change syncs to github

**Comment by smarthi** [comment]
+1 to merge this

**Comment by jfrazee** [comment]
@steveblackmon @smarthi It looks like it still hasn't sync'd back. This went in during that hiccup, so we can either close it and lose the record of the PR or merge it again.

**Pull request closed without merging**
